---

################################################################################
#  description: Installs Jenkins on CentOS7x
#  usage: ansible-playbook CentOS7x_Install-Jenkins-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install Jenkins on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  vars:
    jenkins_home: /var/lib/jenkins
    jenkins_admin_username: admin
    jenkins_admin_password: admin
  tasks:


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install the Java JRE runtime java
    yum:
      name=java-1.8.0-openjdk
      state=latest

  - name: Install the Java JDK compiler javac
    yum:
      name=java-1.8.0-openjdk-devel
      state=latest

  - name: Install Groovy language for Java
    yum:
      name=groovy
      state=latest


# Update various configuration files
# REF: http://docs.ansible.com/ansible/lineinfile_module.html
#############################################################

  - name: Set JAVA_HOME environment variable for root on next login
    lineinfile:
      dest=/root/.bash_profile
      state=present
      line='export JAVA_HOME=/usr/lib/jvm/java-openjdk'

  - name: Set JRE_HOME environment variable for root on next login
    lineinfile:
      dest=/root/.bash_profile
      state=present
      line='export JRE_HOME=/usr/lib/jvm/java-openjdk/jre'

  - name: Add Java to the path for root on next login
    lineinfile:
      dest=/root/.bash_profile
      state=present
      line='export PATH=$PATH:/usr/lib/jvm/java-openjdk/bin:/usr/lib/jvm/java-openjdk/jre/bin'


# Install or configure repository used on the OS by yum
# REF: https://docs.ansible.com/ansible/yum_repository_module.html
##################################################################

# /etc/yum.repos.d/jenkins.repo
  - name: Install repository Jenkins
    yum_repository:
      name: Jenkins
      description: Jenkins repository
      file: jenkins
      baseurl: http://pkg.jenkins.io/redhat
      enabled: yes
      gpgcheck: yes
      gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install Jenkins
    yum:
      name=jenkins
      state=latest


# Restart firewalld to make sure it is running OK before changing any rules
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Ensure the firewalld service is enabled and re-started before changing any rules
    service:
      name=firewalld
      enabled=yes
      state=restarted


# Update the firewalld configuration
# REF: http://docs.ansible.com/ansible/firewalld_module.html
############################################################

  - name: Update firewall to allow port TCP 8080 for incoming Jenkins HTTP connections
    firewalld:
      port=8080/tcp
      permanent=true
      immediate=yes
      state=enabled
      zone=public

  - name: Update firewall to allow port TCP 49187 for incoming Jenkins JNLP connections
    firewalld:
      port=49187/tcp
      permanent=true
      immediate=yes
      state=enabled
      zone=public


# lineinfile - Ensure a particular line is in a file, or replace an existing line using a back-referenced regular expression
# REF: http://docs.ansible.com/ansible/lineinfile_module.html
#############################################################

  - name: Configure Jenkins service to skip the setup wizard
    lineinfile:
      dest: /etc/sysconfig/jenkins
      regexp: '^JENKINS_JAVA_OPTIONS=' 
      line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'


# Enable and start Jenkins service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start Jenkins service
    service:
      name=jenkins
      enabled=yes
      state=restarted

