---

################################################################################
#  description: Installs Mosquitto on CentOS7x
#  usage: ansible-playbook CentOS7x_Install-Mosquitto-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install Mosquitto on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install or configure repository used on the OS by yum
# REF: https://docs.ansible.com/ansible/yum_repository_module.html
##################################################################

# /etc/yum.repos.d/mosquitto.repo
# https://mosquitto.org/download/
  - name: Install repository Mosquitto
    yum_repository:
      name: mosquitto
      description: Mosquitto Repository
      file: mosquitto
      baseurl: http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-7/
      enabled: yes
      gpgcheck: yes
      gpgkey: http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-7//repodata/repomd.xml.key


# Install yum packages (listed in alphabetical order)
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install mosquitto
    yum:
      name=mosquitto
      state=latest

  - name: Install mosquitto-clients
    yum:
      name=mosquitto-clients
      state=latest

  - name: Install libmosquitto1
    yum:
      name=libmosquitto1
      state=latest

  - name: Install libmosquitto-devel
    yum:
      name=libmosquitto-devel
      state=latest

  - name: Install libmosquittopp1
    yum:
      name=libmosquittopp1
      state=latest

  - name: Install libmosquittopp-devel
    yum:
      name=libmosquittopp-devel
      state=latest


# Restart firewalld to make sure it is running OK before changing any rules
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Ensure the firewalld service is enabled and re-started before changing any rules
    service:
      name: firewalld
      enabled: yes
      state: restarted


# Update the firewalld configuration
# REF: http://docs.ansible.com/ansible/firewalld_module.html
############################################################

  - name: Update firewall to allow port TCP 1883 for incoming mosquitto connections
    firewalld:
      port: 1883/tcp
      permanent: true
      immediate: yes
      state: enabled
      zone: public

  - name: Update firewall to allow port TCP 8883 for incoming encrypted mosquitto connections
    firewalld:
      port: 8883/tcp
      permanent: true
      immediate: yes
      state: enabled
      zone: public


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /usr/lib/systemd/system/mosquitto.service
  - name: Copy mosquitto.service from Ansible files/Mosquitto/mosquitto.service to Mosquitto remote /usr/lib/systemd/system/mosquitto.service
    copy:
      src=files/Mosquitto/mosquitto.service
      dest=/usr/lib/systemd/system/mosquitto.service
      owner=root
      group=root
      mode=0400


# Use the template module to populate files with data
# REF: http://docs.ansible.com/ansible/template_module.html
###########################################################

# /etc/mosquitto/mosquitto.conf
  - name: Fill in the variables and copy templates/Mosquitto/mosquitto.conf.j2 from Ansible to Mosquitto remote /etc/mosquitto/mosquitto.conf
    template:
      src=templates/Mosquitto/mosquitto.conf.j2
      dest=/etc/mosquitto/mosquitto.conf
      owner=root
      group=root
      mode=0644


# Start mosquitto
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Ensure the mosquitto service is enabled and started
    service:
      name=mosquitto.service
      enabled=yes
      state=restarted
