---

################################################################################
#  description: Installs Docker on CentOS7x
#  usage: ansible-playbook CentOS7x_Install-Docker-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install Docker on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Configure OS Services
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Stop and disable firewalld
    service:
      name: firewalld
      enabled: no
      state: stopped


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install iptables
    yum:
      name: iptables
      state: latest

  - name: Install bridge-utils
    yum:
      name: bridge-utils
      state: latest
      # brctl show


# Configure OS Services
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start iptables
    service:
      name: iptables
      enabled: yes
      state: restarted


# Execute command(s)
# REF: http://docs.ansible.com/ansible/command_module.html
##########################################################

  - name: /usr/libexec/iptables/iptables.init save
    command: /usr/libexec/iptables/iptables.init save
