---

################################################################################
#  description: Generates and installs a new replication key to a GROUP of MongoDB 3x servers on CentOS7x
#  usage: CentOS7x_Generate-and-Install-new-MongoDB-Replication-Key-playbook.yml --extra-vars 'HostOrGroup=YourGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Generate prerequistite MongoDB replication key on the Ansible host
  hosts: localhost
  serial: "100%"
  gather_facts: False
  tasks:

# Execute raw command(s)
# REF: http://docs.ansible.com/ansible/raw_module.html
##########################################################

  - name: /usr/bin/openssl rand -base64 756 > /tmp/mongod-replication.key
    raw: /usr/bin/openssl rand -base64 756 > /tmp/mongod-replication.key


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: install a new replication key to a GROUP of MongoDB 3x servers on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /var/lib/mongo/mongod-replication.key
  - name: Copy temporary Ansible local file /tmp/mongod-replication.key to MongoDB remote /var/lib/mongo/mongod-replication.key
    copy:
      src=/tmp/mongod-replication.key
      dest=/var/lib/mongo/mongod-replication.key
      owner=mongod
      group=mongod
      mode=0400


# Enable and start mongod service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Re-start the mongod service
    service:
      name=mongod.service
      enabled=yes
      state=restarted
      # Note: Command line verification:
      # systemctl status mongod.service
      # systemctl status mongod.service -l
      # service mongod status
      # ls /var/lib/mongo
      # cat /var/log/messages | grep mongod
      # cat /usr/lib/systemd/system/mongod.service
      # cat /etc/mongod.conf
      # cat /var/log/mongodb/mongod.log


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Post deployment cleanup of the MongoDB replication key from the temporary location on the Ansible host
  hosts: localhost
  serial: "100%"
  gather_facts: False
  tasks:

# Use the file module
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: rm /tmp/mongod-replication.key
    file:
      path: /tmp/mongod-replication.key
      state: absent
