---

################################################################################
#  description: Create Online Flight Recorder (OFR) servers in Control at CenturyLink Cloud
#  usage: ansible-playbook CLC_Create-OFR-Servers-in-VA1-playbook.yml
#  example: ansible-playbook CLC_Create-OFR-Servers-in-VA1-playbook.yml --extra-vars 'Name=OFRTA Password=P@$$W0rd!'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Create Online Flight Recorder (OFR) servers in Control
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:


# clc_server - Create, Delete, Start and Stop servers in CenturyLink Cloud
# REF: http://docs.ansible.com/ansible/clc_server_module.html
#############################################################

# OFR-NGIX servers
    - name: Create OFR-NGIX servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "2"
        group: "VA1_OFR-NGIX"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Logstash servers
    - name: Create OFR-Logstash servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "VA1_OFR-Logstash"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Kafka servers
    - name: Create OFR-Kafka servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "VA1_OFR-Kafka"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-ElasticsearchClientNodes servers
    - name: Create OFR-ElasticsearchClientNodes servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "VA1_OFR-ElasticsearchClientNodes"
        cpu: "2"
        memory: "4"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-ElasticsearchMasterNodes servers
    - name: Create OFR-ElasticsearchMasterNodes servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "VA1_OFR-ElasticsearchMasterNodes"
        cpu: "2"
        memory: "4"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-ElasticsearchDataNodes servers
    - name: Create OFR-ElasticsearchDataNodes servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "VA1_OFR-ElasticsearchDataNodes"
        cpu: "2"
        memory: "4"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Kibana servers
    - name: Create OFR-Kibana servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "VA1_OFR-Kibana"
        cpu: "2"
        memory: "4"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Graylog servers
    - name: Create OFR-Graylog servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "VA1_OFR-Graylog"
        cpu: "2"
        memory: "4"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-MongoDB servers
    - name: Create OFR-MongoDB servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "VA1_OFR-MongoDB"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-StatsD servers
    - name: Create OFR-StatsD servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "1"
        group: "VA1_OFR-StatsD"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Graphite servers
    - name: Create OFR-Graphite servers
      clc_server:
        location: "VA1"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "1"
        group: "VA1_OFR-Graphite"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True
