---

################################################################################
#  description: Create Online Flight Recorder (OFR) servers in Control at CenturyLink Cloud
#  usage: ansible-playbook CLC_Create-OFR-Servers-playbook.yml
#  example: ansible-playbook CLC_Create-OFR-Servers-playbook.yml --extra-vars 'DC=VA1 Name=OFRTA Password=P@$$W0rd!'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Create Online Flight Recorder (OFR) servers in Control
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:


# clc_server - Create, Delete, Start and Stop servers in CenturyLink Cloud
# REF: http://docs.ansible.com/ansible/clc_server_module.html
#############################################################

# OFR-NGINX servers
    - name: Create OFR-NGINX servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR NGIX HA server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "2"
        group: "OFR-NGINX"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Logstash servers
    - name: Create OFR-Logstash servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR Logstash server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "OFR-Logstash"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Kafka servers
    - name: Create OFR-Kafka servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR Kafka server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "OFR-Kafka"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-ElasticsearchClientNodes servers
    - name: Create OFR-ElasticsearchClientNodes servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR Elasticsearch Client Node server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "OFR-ElasticsearchClientNodes"
        cpu: "2"
        memory: "4"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-ElasticsearchMasterNodes servers
    - name: Create OFR-ElasticsearchMasterNodes servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR Elasticsearch Master Node server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "OFR-ElasticsearchMasterNodes"
        cpu: "2"
        memory: "4"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-ElasticsearchDataNodes servers
    - name: Create OFR-ElasticsearchDataNodes servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR Elasticsearch Data Node server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "OFR-ElasticsearchDataNodes"
        cpu: "2"
        memory: "4"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Kibana servers
    - name: Create OFR-Kibana servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR Kibana server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "OFR-Kibana"
        cpu: "2"
        memory: "4"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Graylog servers
    - name: Create OFR-Graylog servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR Graylog server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "OFR-Graylog"
        cpu: "2"
        memory: "4"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-MongoDB servers
    - name: Create OFR-MongoDB servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR MongoDB server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "3"
        group: "OFR-MongoDB"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-StatsD servers
    - name: Create OFR-StatsD servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR StatsD server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "1"
        group: "OFR-StatsD"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Graphite servers
    - name: Create OFR-Graphite servers
      ignore_errors: yes
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "OFR Graphite server"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "1"
        group: "OFR-Graphite"
        cpu: "2"
        memory: "2"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True
