---

################################################################################
#  description: Create Online Flight Recorder (OFR) servers in Control at CenturyLink Cloud
#  usage: ansible-playbook CLC_Create-OFR-Servers-In-Control-playbook.yml
#  example: ansible-playbook CLC_Create-OFR-Servers-In-Control-playbook.yml --extra-vars 'DC=VA1 Name=OFRTZ Password=P@$$W0rd!'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Create Online Flight Recorder (OFR) servers in Control
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:


# clc_server - Create, Delete, Start and Stop servers in CenturyLink Cloud
# REF: http://docs.ansible.com/ansible/clc_server_module.html
#############################################################

# OFR-NGIX servers
    - name: Create OFR-NGIX servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR NGIX HA server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('2') }}"
        group: "{{ Group|default ('OFR-NGIX') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('2') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Logstash servers
    - name: Create OFR-Logstash servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR Logstash server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('3') }}"
        group: "{{ Group|default ('OFR-Logstash') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('2') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Kafka servers
    - name: Create OFR-Kafka servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR Kafka server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('3') }}"
        group: "{{ Group|default ('OFR-Kafka') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('2') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-ElasticsearchClientNodes servers
    - name: Create OFR-ElasticsearchClientNodes servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR Elasticsearch Client Node server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('3') }}"
        group: "{{ Group|default ('OFR-ElasticsearchClientNodes') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('4') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-ElasticsearchMasterNodes servers
    - name: Create OFR-ElasticsearchMasterNodes servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR Elasticsearch Master Node server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('3') }}"
        group: "{{ Group|default ('OFR-ElasticsearchMasterNodes') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('4') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-ElasticsearchDataNodes servers
    - name: Create OFR-ElasticsearchDataNodes servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR Elasticsearch Data Node server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('3') }}"
        group: "{{ Group|default ('OFR-ElasticsearchDataNodes') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('4') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Kibana servers
    - name: Create OFR-Kibana servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR Kibana server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('3') }}"
        group: "{{ Group|default ('OFR-Kibana') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('4') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Graylog servers
    - name: Create OFR-Graylog servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR Graylog server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('3') }}"
        group: "{{ Group|default ('OFR-Graylog') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('4') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-MongoDB servers
    - name: Create OFR-MongoDB servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR MongoDB server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('3') }}"
        group: "{{ Group|default ('OFR-MongoDB') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('2') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-StatsD servers
    - name: Create OFR-StatsD servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR StatsD server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('1') }}"
        group: "{{ Group|default ('OFR-StatsD') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('2') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True

# OFR-Graphite servers
    - name: Create OFR-Graphite servers
      clc_server:
        location: "{{ DC|default ('VA1') }}"
        password: "{{ Password|default ('P@$$W0rd!') }}"
        name: "{{ Name|default ('OFRTZ') }}"
        description: "{{ Description|default ('OFR Graphite server') }}"
        template: "{{ Template|default ('CENTOS-7-64-TEMPLATE') }}"
        count: "{{ Count|default ('1') }}"
        group: "{{ Group|default ('OFR-Graphite') }}"
        cpu: "{{ CPU|default ('2') }}"
        memory: "{{ Memory|default ('2') }}"
        primary_dns: "{{ DNS1|default ('172.17.1.26') }}"
        secondary_dns: "{{ DNS2|default ('172.17.1.27') }}"
        wait: True
