---

################################################################################
#  description: Apply updates to Chrysus on RHEL7x
#  usage: ansible-playbook RHEL7x_Apply-Chrysus-Updates-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Apply updates to Chrysus on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: Update Chrysus Engine
    shell: cd /opt/chrysus; /usr/bin/npm install chrysus


# Restart the service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Restart the chrysus service
    service:
      name=chrysus.service
      enabled=yes
      state=restarted
      # Note: Verify chrysus via SSH command line:
      # systemctl status chrysus
